package jp.co.sample.mapper;

import java.util.List;
import jp.co.sample.mapper.TUserActionLogs;
import jp.co.sample.mapper.TUserActionLogsExample;
import org.apache.ibatis.annotations.Param;

public interface TUserActionLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    long countByExample(TUserActionLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int deleteByExample(TUserActionLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int insert(TUserActionLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int insertSelective(TUserActionLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    List<TUserActionLogs> selectByExample(TUserActionLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    TUserActionLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int updateByExampleSelective(@Param("record") TUserActionLogs record, @Param("example") TUserActionLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int updateByExample(@Param("record") TUserActionLogs record, @Param("example") TUserActionLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int updateByPrimaryKeySelective(TUserActionLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_action_logs
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    int updateByPrimaryKey(TUserActionLogs record);
}