package jp.co.sample.mapper;

import java.util.Date;

public class TUserActionLogs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_action_logs.id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_action_logs.customer_id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_action_logs.event_id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_action_logs.created_at
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_action_logs.id
     *
     * @return the value of t_user_action_logs.id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_action_logs.id
     *
     * @param id the value for t_user_action_logs.id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_action_logs.customer_id
     *
     * @return the value of t_user_action_logs.customer_id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_action_logs.customer_id
     *
     * @param customerId the value for t_user_action_logs.customer_id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_action_logs.event_id
     *
     * @return the value of t_user_action_logs.event_id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_action_logs.event_id
     *
     * @param eventId the value for t_user_action_logs.event_id
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_action_logs.created_at
     *
     * @return the value of t_user_action_logs.created_at
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_action_logs.created_at
     *
     * @param createdAt the value for t_user_action_logs.created_at
     *
     * @mbg.generated Sun Nov 11 23:40:49 JST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}